---
version: "2.0"

# Optimized Akash deployment for ~$50/month
# Removed Qdrant (using ICP canister instead)
# Reduced resource allocations to cost-effective levels

services:
  nginx:
    image: ghcr.io/lain-corp/lain-tv/nginx:latest
    build:
      context: https://github.com/lain-corp/lain-tv.git
      dockerfile: backend/nginx/Dockerfile
    expose:
      - port: 80
        as: 80
        to:
          - global: true
        accept:
          - lain.tv
          - www.lain.tv
    depends_on:
      - websocket
      - lainllm

  redis:
    image: redis:7-alpine
    expose:
      - port: 6379
        as: 6379
        to:
          - service: lainllm
          - service: websocket
          - service: tts
          - service: animation
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--maxmemory"
      - "256mb"
      - "--maxmemory-policy"
      - "allkeys-lru"

  lainllm:
    # Build directly from GitHub repository
    # Uses ICP canister for knowledge (no Qdrant needed)
    image: ghcr.io/lain-corp/lain-tv/lainllm:latest
    build:
      context: https://github.com/lain-corp/lain-tv.git
      dockerfile: backend/ai-agent/Dockerfile
    expose:
      - port: 8001
        as: 8001
        to:
          - service: nginx
          - service: websocket
    env:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ICP_CANISTER_ID=zbpu3-baaaa-aaaad-qhpha-cai
      - ICP_HOST=https://ic0.app
      - MODEL_PATH=/models/lain-model.gguf
      - N_THREADS=4
      - N_CTX=4096
      - N_BATCH=512
      - TEMPERATURE=0.8
      - MAX_TOKENS=150

  websocket:
    image: ghcr.io/lain-corp/lain-tv/websocket:latest
    build:
      context: https://github.com/lain-corp/lain-tv.git
      dockerfile: backend/websocket/Dockerfile
    expose:
      - port: 8080
        as: 8080
        to:
          - service: nginx
    depends_on:
      - lainllm
      - redis
    env:
      - LAINLLM_URL=http://lainllm:8001
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  tts:
    image: ghcr.io/lain-corp/lain-tv/tts:latest
    build:
      context: https://github.com/lain-corp/lain-tv.git
      dockerfile: backend/tts/Dockerfile
    expose:
      - port: 8002
        as: 8002
        to:
          - service: nginx
          - service: websocket
    env:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  animation:
    image: ghcr.io/lain-corp/lain-tv/animation:latest
    build:
      context: https://github.com/lain-corp/lain-tv.git
      dockerfile: backend/animation/Dockerfile
    expose:
      - port: 8003
        as: 8003
        to:
          - service: nginx
          - service: websocket
    env:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

profiles:
  compute:
    nginx:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          size: 512Mi
    
    lainllm:
      resources:
        cpu:
          units: 4
        memory:
          size: 6Gi
        storage:
          size: 10Gi
    
    redis:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    
    websocket:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    
    tts:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    
    animation:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          size: 512Mi

  placement:
    akash:
      pricing:
        nginx:
          denom: uakt
          amount: 1000
        lainllm:
          denom: uakt
          amount: 5000
        redis:
          denom: uakt
          amount: 1000
        websocket:
          denom: uakt
          amount: 1000
        tts:
          denom: uakt
          amount: 2000
        animation:
          denom: uakt
          amount: 1000

deployment:
  nginx:
    akash:
      profile: nginx
      count: 1
  lainllm:
    akash:
      profile: lainllm
      count: 1
  redis:
    akash:
      profile: redis
      count: 1
  websocket:
    akash:
      profile: websocket
      count: 1
  tts:
    akash:
      profile: tts
      count: 1
  animation:
    akash:
      profile: animation
      count: 1
