---
version: "2.0"

services:
  redis:
    image: redis:7-alpine
    expose:
      - port: 6379
        as: 6379
        to:
          - service: lainllm
          - service: websocket
          - service: tts
          - service: animation
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--maxmemory"
      - "512mb"
      - "--maxmemory-policy"
      - "allkeys-lru"

  qdrant:
    image: qdrant/qdrant:latest
    expose:
      - port: 6333
        as: 6333
        to:
          - service: lainllm
      - port: 6334
        as: 6334
        to:
          - service: lainllm
    env:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__MAX_REQUEST_SIZE_MB=32

  lainllm:
    image: openregistry.dev/laincorp/lainllm:latest
    expose:
      - port: 8001
        as: 8001
        to:
          - service: websocket
          - global: true
    env:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - MODEL_PATH=/models/lain-model.gguf
      - MODEL_TYPE=llama.cpp
      - N_THREADS=16
      - N_CTX=4096
      - N_BATCH=512
      - LAIN_PERSONALITY_MODE=cryptic
      - TEMPERATURE=0.8
      - MAX_TOKENS=150
      - VECTOR_COLLECTION=lain_memory
      - TOP_P=0.9
      - REPEAT_PENALTY=1.1
    depends_on:
      - redis
      - qdrant

  tts:
    image: openregistry.dev/laincorp/laintts:latest
    expose:
      - port: 8002
        as: 8002
        to:
          - service: websocket
    env:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TTS_ENGINE=piper
      - PIPER_MODEL=en_US-lessac-medium
      - OUTPUT_PATH=/output
      - SPEAKER_ID=0
      - LENGTH_SCALE=1.0
      - NOISE_SCALE=0.667
    depends_on:
      - redis

  animation:
    image: openregistry.dev/laincorp/lainanimation:latest
    expose:
      - port: 8003
        as: 8003
        to:
          - service: websocket
    env:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IDLE_INTERVAL=30
      - MOOD_STATES=idle,curious,thoughtful,cryptic,surprised,distant,melancholic
      - DEFAULT_ANIMATION=idle
      - ANIMATION_BLEND_TIME=0.5
    depends_on:
      - redis

  websocket:
    image: openregistry.dev/laincorp/lainwebsocket:latest
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AI_AGENT_URL=http://lainllm:8001
      - TTS_URL=http://tts:8002
      - ANIMATION_URL=http://animation:8003
      - RATE_LIMIT_MESSAGES=10
      - RATE_LIMIT_WINDOW=60
      - MAX_MESSAGE_LENGTH=500
      - ENABLE_ICP_VERIFICATION=true
      - WS_PORT=8080
      - MAX_CONNECTIONS=1000
      - PING_INTERVAL=30000
      - PING_TIMEOUT=5000
    depends_on:
      - redis
      - lainllm
      - tts
      - animation

profiles:
  compute:
    redis:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 2Gi
    qdrant:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          size: 10Gi
    lainllm:
      resources:
        cpu:
          units: 16
        memory:
          size: 12Gi
        storage:
          size: 10Gi
    tts:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          size: 2Gi
    animation:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi
    websocket:
      resources:
        cpu:
          units: 2
        memory:
          size: 1Gi
        storage:
          size: 512Mi

  placement:
    akash:
      pricing:
        redis:
          denom: uakt
          amount: 1000
        qdrant:
          denom: uakt
          amount: 5000
        lainllm:
          denom: uakt
          amount: 20000
        tts:
          denom: uakt
          amount: 3000
        animation:
          denom: uakt
          amount: 1000
        websocket:
          denom: uakt
          amount: 2000

deployment:
  redis:
    akash:
      profile: redis
      count: 1
  qdrant:
    akash:
      profile: qdrant
      count: 1
  lainllm:
    akash:
      profile: lainllm
      count: 1
  tts:
    akash:
      profile: tts
      count: 1
  animation:
    akash:
      profile: animation
      count: 1
  websocket:
    akash:
      profile: websocket
      count: 1
